spring:
  datasource:
    url: jdbc:mysql://101.132.116.166:3306/ad_monitor
    username: root
    password: pass1234
    driver-class-name: com.mysql.cj.jdbc.Driver
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
    consumer:
      auto-offset-reset: earliest
logging:
  level:
    org.apache.kafka.clients.NetworkClient: ERROR  # 只显示 WARN 及以上级别日志
    org.springframework.kafka: ERROR              # 关闭 Spring Kafka 冗余日志
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl  # 启用 SQL 日志
  mapper-locations: classpath:mapper/*.xml                 # XML 映射文件路径
  type-aliases-package: com.cqyang.adMonitor.model.po       # 实体类包路径

kafka-topic:
  access:
    self-ad: self_ad
  audit:
    common-audit: common_audit
    high-priority-audit: hight_priority_audit
