spring:
  datasource:
    url: jdbc:mysql://101.132.116.166:3306/crawler
    username: root
    password: pass1234
    driver-class-name: com.mysql.cj.jdbc.Driver
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
    consumer:
      auto-offset-reset: earliest

access:
  kafka-topic:
    self-ad: self_ad